Io serialization
Gavialll/Java pull request #15
Opened 2021-03-28 17:52 UTC by Gavialll

2021-04-03 22:10 UTC, ValentinTyhonov requested changes

2021-04-03 22:10 UTC, ValentinTyhonov commented on src/IOSerialization/Methods.java
> +public class Methods<T> implements Serializable {
цей клас не повинен імплементувати Serializable. Ти ж не будеш сереалізувати об'єкти класу Methods

2021-04-03 22:10 UTC, ValentinTyhonov commented on src/IOSerialization/Start.java
> +        Methods methods = new Methods();
нема сенсу створювати об'єкт класу Methods. Його методи можуть бути статичними

2021-04-03 22:10 UTC, ValentinTyhonov commented on src/IOSerialization/Start.java
> +        List<Employee> test = (List<Employee>) methods.deSerialize("/sers/andrijdutko/Desktop/GitJava/src/IOSerialization/Object");
Тут не потрібно робити приведення типів, оскільки воно вже зроблено в методі deSerialize

2021-04-04 15:44 UTC, Gavialll commented on src/IOSerialization/Start.java
> +        Methods methods = new Methods();
Мені через дженерики невиходить зробити їх статичними

2021-04-04 21:56 UTC, Gavialll commented on src/IOSerialization/Start.java
> +        Methods methods = new Methods();
Все поправив

2021-04-06 21:40 UTC, ValentinTyhonov approved these changes

2021-04-06 21:40 UTC, merged