DZJava
Gavialll/Java pull request #2
Opened 2021-02-21 23:33 UTC by Gavialll

2021-02-21 23:53 UTC, ValentinTyhonov requested changes

2021-02-21 23:53 UTC, ValentinTyhonov commented on src/Rectangle/RectanglePerimeter.java
> +public class RectanglePerimeter {
Для чого робити 2 окремих класи. Мав би бути один клас Rectangle із методами для пошуку площі і периметру.

2021-02-21 23:53 UTC, ValentinTyhonov commented on src/Game/Start.java
> +                    man[random].setHp(damage);
спробуй зробити, щоб метод attack приймав параметр типу Man (кого атакують) і скоротити ці 2 рядки

2021-02-22 10:57 UTC, Gavialll commented on src/Rectangle/RectanglePerimeter.java
> +public class RectanglePerimeter {
Ну та поправлю

2021-02-23 11:04 UTC, Gavialll commented on src/Game/Start.java
> +                    man[random].setHp(damage);
Все поправив

2021-02-23 18:26 UTC, ValentinTyhonov approved these changes

2021-02-23 18:26 UTC, merged